import fs from 'node:fs'
import path from 'node:path'
import readline from 'node:readline/promises'
import { stdin, stdout } from 'node:process'
import { spawnSync } from 'node:child_process'
import { HOME_DIR, GITIGNORE_PATH } from '../paths.ts'

const DEFAULT_GITIGNORE = `# generated by browser-cli
db.sqlite
db.sqlite-*
feeds/
.cache/
.env
daemon.pid
daemon.log
node_modules
`

function runGit(args: string[], opts: { cwd?: string } = {}): { code: number; stdout: string; stderr: string } {
  const res = spawnSync('git', args, {
    cwd: opts.cwd ?? HOME_DIR,
    encoding: 'utf8',
  })
  return {
    code: res.status ?? -1,
    stdout: res.stdout ?? '',
    stderr: res.stderr ?? '',
  }
}

export function isUserRepoInit(): boolean {
  return fs.existsSync(path.join(HOME_DIR, '.git'))
}

export function writeGitignoreIfMissing(): void {
  if (fs.existsSync(GITIGNORE_PATH)) return
  fs.writeFileSync(GITIGNORE_PATH, DEFAULT_GITIGNORE, 'utf8')
}

// Idempotent: runs `git init` + writes .gitignore only when `.git` is missing.
// Returns whether initialization actually happened this call.
export function ensureUserRepo(): { justInitialized: boolean } {
  if (isUserRepoInit()) {
    writeGitignoreIfMissing()
    return { justInitialized: false }
  }
  if (!fs.existsSync(HOME_DIR)) fs.mkdirSync(HOME_DIR, { recursive: true })
  const res = runGit(['init', '-q', '-b', 'main'])
  if (res.code !== 0) {
    // fall back for older git (no -b flag)
    runGit(['init', '-q'])
  }
  writeGitignoreIfMissing()
  return { justInitialized: true }
}

export type StatusEntry = { path: string; status: 'added' | 'modified' | 'deleted' | 'untracked' | 'other' }

export function statusSummary(): { entries: StatusEntry[]; hasChanges: boolean } {
  if (!isUserRepoInit()) return { entries: [], hasChanges: false }
  const res = runGit(['status', '--porcelain=v1'])
  if (res.code !== 0) return { entries: [], hasChanges: false }
  const entries: StatusEntry[] = []
  for (const line of res.stdout.split('\n')) {
    if (!line) continue
    const code = line.slice(0, 2)
    const p = line.slice(3).trim()
    entries.push({ path: p, status: classify(code) })
  }
  return { entries, hasChanges: entries.length > 0 }
}

function classify(code: string): StatusEntry['status'] {
  if (code === '??') return 'untracked'
  if (code.includes('D')) return 'deleted'
  if (code.includes('A')) return 'added'
  if (code.includes('M')) return 'modified'
  return 'other'
}

export function diffAll(): string {
  if (!isUserRepoInit()) return ''
  runGit(['add', '-N', '-A'])
  const res = runGit(['diff', 'HEAD', '--'])
  if (res.code === 0) return res.stdout
  const staged = runGit(['diff', '--cached'])
  return staged.stdout
}

export function commitAll(message: string): { code: number; output: string } {
  runGit(['add', '-A'])
  const res = runGit(['commit', '-m', message])
  return { code: res.code, output: res.stdout + res.stderr }
}

export function hasRemote(): boolean {
  const res = runGit(['remote'])
  return res.code === 0 && res.stdout.trim().length > 0
}

export function isAheadOfRemote(): boolean {
  const upstream = runGit(['rev-parse', '--abbrev-ref', '--symbolic-full-name', '@{u}'])
  if (upstream.code !== 0) return false
  const cmp = runGit(['rev-list', '--count', '@{u}..HEAD'])
  if (cmp.code !== 0) return false
  return Number(cmp.stdout.trim()) > 0
}

export function pushToRemote(): { code: number; output: string } {
  const res = runGit(['push'])
  return { code: res.code, output: res.stdout + res.stderr }
}

// Interactive commit flow. On TTY: prompts [y/n/d/s]. Non-TTY: prints a hint
// and returns without asking so CI / sub-agents never block.
export async function promptAndCommit(trigger: string): Promise<void> {
  if (!isUserRepoInit()) return
  const status = statusSummary()
  if (!status.hasChanges) return

  if (!stdout.isTTY || !stdin.isTTY) {
    process.stderr.write(
      `uncommitted changes in ${HOME_DIR} — run 'browser-cli sync' to commit\n`,
    )
    return
  }

  const rl = readline.createInterface({ input: stdin, output: stdout })
  try {
    printStatus(status.entries)
    while (true) {
      const ans = (await rl.question(
        `commit these changes? [y]es / [n]o / [d]iff / [s]how files: `,
      )).trim().toLowerCase()
      if (ans === 'y' || ans === 'yes') {
        const msg = defaultCommitMessage(status.entries, trigger)
        const res = commitAll(msg)
        if (res.code === 0) {
          process.stdout.write(`committed: ${msg}\n`)
          if (hasRemote() && isAheadOfRemote()) {
            const push = (await rl.question(`push to remote? [y/N]: `)).trim().toLowerCase()
            if (push === 'y' || push === 'yes') {
              const pr = pushToRemote()
              process.stdout.write(pr.output)
            }
          }
        } else {
          process.stderr.write(res.output)
        }
        return
      }
      if (ans === 'n' || ans === 'no' || ans === '') {
        process.stdout.write(
          `skipped — run 'browser-cli sync' later to commit\n`,
        )
        return
      }
      if (ans === 'd' || ans === 'diff') {
        const d = diffAll()
        process.stdout.write(d || '(no diff — only untracked files)\n')
        continue
      }
      if (ans === 's' || ans === 'show') {
        printStatus(status.entries)
        continue
      }
    }
  } finally {
    rl.close()
  }
}

function printStatus(entries: StatusEntry[]): void {
  const label: Record<StatusEntry['status'], string> = {
    added: 'new    ',
    modified: 'changed',
    deleted: 'deleted',
    untracked: 'new    ',
    other: '       ',
  }
  for (const e of entries) {
    process.stdout.write(`  ${label[e.status]}  ${e.path}\n`)
  }
}

function defaultCommitMessage(entries: StatusEntry[], trigger: string): string {
  const paths = entries.map((e) => e.path)
  if (paths.length === 1) {
    const e = entries[0]!
    const verb = e.status === 'deleted' ? 'remove' : e.status === 'modified' ? 'update' : 'add'
    return `${verb} ${e.path}`
  }
  const byDir = new Set(paths.map((p) => p.split('/')[0]))
  const scope = byDir.size === 1 ? [...byDir][0] : 'home'
  return `update ${scope} (${paths.length} files) — ${trigger}`
}
